#!/usr/bin/env bash
# Shared state and config generation for yanvpn.
#
# Design: /etc/yanvpn/clients/<name>/meta is the single source of truth. Every
# protocol config (wg0.conf, awg0.conf, sing-box users) is *regenerated* from
# that registry rather than surgically edited. Adding a client is one command
# regardless of how many transports are installed.

# Paths are overridable so the generation logic can be exercised without root.
YANVPN_DIR=${YANVPN_DIR:-/etc/yanvpn}
CONFIG=$YANVPN_DIR/config
SERVER_ENV=$YANVPN_DIR/server.env
CLIENTS=$YANVPN_DIR/clients
WG_DIR=${WG_DIR:-/etc/wireguard}
AWG_DIR=${AWG_DIR:-/etc/amnezia/amneziawg}
SB_DIR=${SB_DIR:-/etc/sing-box}
SB_CONF=$SB_DIR/config.json

BOLD=$'\e[1m'; RED=$'\e[31m'; GRN=$'\e[32m'; YEL=$'\e[33m'; DIM=$'\e[2m'; RST=$'\e[0m'
say()  { printf '%s==>%s %s\n' "$BOLD" "$RST" "$*"; }
ok()   { printf '  %s✓%s %s\n' "$GRN" "$RST" "$*"; }
warn() { printf '  %s!%s %s\n' "$YEL" "$RST" "$*"; }
info() { printf '  %s·%s %s\n' "$DIM" "$RST" "$*"; }
die()  { printf '%s✗ %s%s\n' "$RED" "$*" "$RST" >&2; exit 1; }

load_config() {
  [[ -r $CONFIG ]] || die "yanvpn is not installed. Run server/install.sh first."
  # shellcheck source=/dev/null
  source "$CONFIG"
  # shellcheck source=/dev/null
  [[ -r $SERVER_ENV ]] && source "$SERVER_ENV"
  : "${WG_IF:=wg0}" "${WG_PORT:=51820}" "${WG_ALT_PORTS:=}"
  : "${AWG_IF:=awg0}" "${AWG_PORT:=51821}" "${AWG_ALT_PORTS:=}"
  : "${WG_NET4:=10.66.66}" "${AWG_NET4:=10.66.67}"
  : "${CLIENT_MTU:=1380}"
}

# Persist a KEY=value into server.env, replacing any prior value.
set_env() {
  local k=$1 v=$2
  install -d -m 700 "$YANVPN_DIR"
  touch "$SERVER_ENV"; chmod 600 "$SERVER_ENV"
  # Always quote: values like ALT_PORTS are multi-word, and an unquoted
  # assignment makes 'source config' try to execute the second word.
  if grep -q "^${k}=" "$SERVER_ENV" 2>/dev/null; then
    sed -i "s|^${k}=.*|${k}=\"${v}\"|" "$SERVER_ENV"
  else
    printf '%s="%s"\n' "$k" "$v" >>"$SERVER_ENV"
  fi
}

set_cfg() {
  local k=$1 v=$2
  if grep -q "^${k}=" "$CONFIG" 2>/dev/null; then
    sed -i "s|^${k}=.*|${k}=\"${v}\"|" "$CONFIG"
  else
    printf '%s="%s"\n' "$k" "$v" >>"$CONFIG"
  fi
}

client_names() {
  local d
  for d in "$CLIENTS"/*/; do
    [[ -d $d && -r ${d}meta ]] || continue
    basename "$d"
  done
}

# Load one client's meta into CL_* variables.
load_client() {
  local name=$1
  [[ -r $CLIENTS/$name/meta ]] || return 1
  # Cleared one per line: "A= B= C=" on one line is valid but reads as an
  # assignment of "B=" to A, and a stale value surviving here would silently
  # leak one client's key into another's generated config.
  local v
  for v in CL_NAME CL_HOST CL_UUID \
           CL_WG_PRIV CL_WG_PUB CL_WG_PSK \
           CL_AWG_PRIV CL_AWG_PUB CL_AWG_PSK; do
    unset "$v"
  done
  # shellcheck source=/dev/null
  source "$CLIENTS/$name/meta"
  return 0
}

next_host_octet() {
  local n used i
  used=$(for n in $(client_names); do
           awk -F= '/^CL_HOST=/{print $2}' "$CLIENTS/$n/meta"
         done)
  for i in $(seq 2 254); do
    grep -qx "$i" <<<"$used" || { echo "$i"; return 0; }
  done
  die "No free addresses left."
}

have_awg()     { [[ -n ${AWG_PRIV:-} ]]; }
have_reality() { [[ -n ${REALITY_PRIV:-} ]]; }

# --------------------------------------------------------------- iptables bits
# Build PostUp/PostDown lines that redirect alternate UDP ports to a real
# listener, plus the NAT/forwarding rules the tunnel needs.
_fw_lines() {
  local dir=$1 port=$2 alts=$3 flag p out=""
  [[ $dir == up ]] && flag=-A || flag=-D
  out+="iptables ${flag} FORWARD -i %i -j ACCEPT"$'\n'
  out+="iptables ${flag} FORWARD -o %i -j ACCEPT"$'\n'
  out+="iptables -t nat ${flag} POSTROUTING -o ${WAN_IF} -j MASQUERADE"$'\n'
  out+="iptables ${flag} INPUT -p udp --dport ${port} -j ACCEPT"$'\n'
  for p in $alts; do
    out+="iptables -t nat ${flag} PREROUTING -i ${WAN_IF} -p udp --dport ${p} -j REDIRECT --to-ports ${port}"$'\n'
  done
  printf '%s' "$out"
}

_emit_fw() {
  local port=$1 alts=$2
  _fw_lines up "$port" "$alts" | sed 's/^/PostUp   = /'
  _fw_lines down "$port" "$alts" | sed 's/^/PostDown = /'
}

# Delete REDIRECT rules aimed at our tunnel ports. wg-quick generates PostDown
# from the *current* config, so changing ALT_PORTS and restarting strands the
# previous rules in PREROUTING, where they keep shadowing the new ones.
flush_yanvpn_redirects() {
  local rule
  iptables -t nat -S PREROUTING 2>/dev/null \
    | grep -E -- "-j REDIRECT --to-ports (${WG_PORT}|${AWG_PORT})$" \
    | sed 's/^-A /-D /' \
    | while read -r rule; do
        # shellcheck disable=SC2086
        iptables -t nat $rule 2>/dev/null || true
      done
}

# ------------------------------------------------------------------ regenerate
regen_wg() {
  local conf=${WG_DIR}/${WG_IF}.conf n
  install -d -m 700 "$WG_DIR"
  {
    echo "# Generated by yanvpn from ${CLIENTS}. Do not edit; changes are overwritten."
    echo "[Interface]"
    echo "Address    = ${WG_NET4}.1/24"
    echo "ListenPort = ${WG_PORT}"
    echo "PrivateKey = ${WG_PRIV}"
    _emit_fw "$WG_PORT" "$WG_ALT_PORTS"
    for n in $(client_names); do
      load_client "$n" || continue
      printf '\n[Peer]\n# yanvpn-client: %s\nPublicKey    = %s\nPresharedKey = %s\nAllowedIPs   = %s.%s/32\n' \
        "$n" "$CL_WG_PUB" "$CL_WG_PSK" "$WG_NET4" "$CL_HOST"
    done
  } >"$conf"
  chmod 600 "$conf"
}

regen_awg() {
  have_awg || return 0
  local conf=${AWG_DIR}/${AWG_IF}.conf n
  install -d -m 700 "$AWG_DIR"
  {
    echo "# Generated by yanvpn. Do not edit; changes are overwritten."
    echo "[Interface]"
    echo "Address    = ${AWG_NET4}.1/24"
    echo "ListenPort = ${AWG_PORT}"
    echo "PrivateKey = ${AWG_PRIV}"
    # Obfuscation parameters. These must match byte-for-byte on the client or
    # the handshake is not merely rejected -- it is unrecognisable.
    echo "Jc  = ${AWG_JC}"
    echo "Jmin = ${AWG_JMIN}"
    echo "Jmax = ${AWG_JMAX}"
    echo "S1  = ${AWG_S1}"
    echo "S2  = ${AWG_S2}"
    echo "H1  = ${AWG_H1}"
    echo "H2  = ${AWG_H2}"
    echo "H3  = ${AWG_H3}"
    echo "H4  = ${AWG_H4}"
    _emit_fw "$AWG_PORT" "$AWG_ALT_PORTS"
    for n in $(client_names); do
      load_client "$n" || continue
      printf '\n[Peer]\n# yanvpn-client: %s\nPublicKey    = %s\nPresharedKey = %s\nAllowedIPs   = %s.%s/32\n' \
        "$n" "$CL_AWG_PUB" "$CL_AWG_PSK" "$AWG_NET4" "$CL_HOST"
    done
  } >"$conf"
  chmod 600 "$conf"
}

regen_reality() {
  have_reality || return 0
  local users n
  users=$(for n in $(client_names); do
            load_client "$n" || continue
            printf '{"uuid":"%s","flow":"xtls-rprx-vision","name":"%s"}\n' "$CL_UUID" "$n"
          done | jq -s '.')
  install -d -m 755 "$SB_DIR"
  jq -n --argjson users "$users" \
        --arg priv "$REALITY_PRIV" --arg sid "$REALITY_SID" \
        --arg sni "$REALITY_SNI" --argjson port "${REALITY_PORT:-443}" '
  {
    log: { level: "warn", timestamp: true },
    inbounds: [{
      type: "vless", tag: "vless-in",
      listen: "::", listen_port: $port,
      users: $users,
      tls: {
        enabled: true,
        server_name: $sni,
        reality: {
          enabled: true,
          handshake: { server: $sni, server_port: 443 },
          private_key: $priv,
          short_id: [$sid]
        }
      }
    }],
    outbounds: [{ type: "direct", tag: "direct" }]
  }' >"$SB_CONF"
  chmod 640 "$SB_CONF"
}

# Apply regenerated configs to the running services without dropping peers.
apply_all() {
  regen_wg; regen_awg; regen_reality

  if systemctl is-active --quiet "wg-quick@${WG_IF}"; then
    wg syncconf "$WG_IF" <(wg-quick strip "$WG_IF")
  fi
  if have_awg && systemctl is-active --quiet "awg-quick@${AWG_IF}"; then
    awg syncconf "$AWG_IF" <(awg-quick strip "$AWG_IF")
  fi
  if have_reality; then
    # sing-box has no live reload; a restart drops connections for ~1s.
    sing-box check -c "$SB_CONF" >/dev/null 2>&1 \
      || die "Generated sing-box config failed validation. Not restarting."
    systemctl is-active --quiet sing-box && systemctl restart sing-box
  fi
}
